# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    border_size = 1
    col.active_border = rgba(ffffff30)
    col.inactive_border = rgba(ffffff10)
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 8

    active_opacity = 0.82
    inactive_opacity = 0.72

    shadow {
        enabled = true
        range = 15
        render_power = 2
        color = rgba(00000035)
    }

    blur {
        enabled = true
        size = 8
        passes = 4
        new_optimizations = true
        xray = false
        noise = 0.04
        contrast = 0.85
        brightness = 1.0
        vibrancy = 0.3
    }
}
